# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

CONFIG_LOG=y

CONFIG_AUDIO=y
CONFIG_AUDIO_CODEC=y
CONFIG_AUDIO_TAC5112=y

CONFIG_I2C=y
CONFIG_GPIO=y

# Needed only if you enable the optional I2S tone playback (tac5112-i2s
# alias). Harmless to leave on otherwise.
CONFIG_I2S=y
